name: wordevents
author: abidibo
category: Utilities
tags: [events, keyboard, words]
docs: http://www.abidibo.net/projects/js/wordevents
demo: http://www.abidibo.net/projects/js/wordevents/demo
current: 0.2.1
